apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner-sa
  namespace: github-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-deployment-role
  namespace: ping-app
rules:
- apiGroups: [""]
  resources: ["services", "configmaps"]
  verbs: ["get", "list", "create", "update", "patch", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "create", "update", "patch", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-runner-app-deployment-binding
  namespace: ping-app
subjects:
- kind: ServiceAccount
  name: github-runner-sa
  namespace: github-runner
roleRef:
  kind: Role
  name: app-deployment-role
  apiGroup: rbac.authorization.k8s.io
