name: Reusable Build and Push Pinger

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles(format('app/{0}/requirements-dev.txt', inputs.app_name)) }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies for linting
        run: pip install -r app/${{ inputs.app_name }}/requirements-dev.txt

      - name: Lint with ruff
        run: ruff check ./app/${{ inputs.app_name }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Build and push ${{ inputs.app_name }} image
        uses: docker/build-push-action@v5
        with:
          context: ./app/${{ inputs.app_name }}
          push: true
          tags: ${{ secrets.docker_username }}/${{ inputs.app_name }}:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
